
from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_infowin(object):
    def setupUi(self, infowin):
        infowin.setObjectName("infowin")
        infowin.resize(752, 540)
        infowin.setMinimumSize(QtCore.QSize(354, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Graphics\\Icons window.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        infowin.setWindowIcon(icon)
        infowin.setStyleSheet("background-color: rgb(255, 255, 255);")
        infowin.setIconSize(QtCore.QSize(41, 40))
        self.centralwidget = QtWidgets.QWidget(infowin)
        self.centralwidget.setObjectName("centralwidget")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 30, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setMouseTracking(False)
        self.label_9.setScaledContents(False)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(-10, -10, 771, 21))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("Graphics\\line.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 530, 311, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(-10, 500, 791, 16))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("Graphics\\line.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(30, 90, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setScaledContents(False)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 140, 301, 101))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(30, 260, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setScaledContents(False)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 310, 301, 101))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(410, 90, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setScaledContents(False)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 130, 301, 171))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(440, 320, 200, 150))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Graphics\\ggiii.png"))
        self.label_4.setObjectName("label_4")
        infowin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(infowin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 26))
        self.menubar.setObjectName("menubar")
        infowin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(infowin)
        self.statusbar.setObjectName("statusbar")
        infowin.setStatusBar(self.statusbar)

        self.retranslateUi(infowin)
        QtCore.QMetaObject.connectSlotsByName(infowin)

    def retranslateUi(self, infowin):
        _translate = QtCore.QCoreApplication.translate
        infowin.setWindowTitle(_translate("infowin", "General Info MChat"))
        self.label_9.setText(_translate("infowin", "General Info"))
        self.label_13.setText(_translate("infowin", "How to use this app ?"))
        self.label.setText(_translate("infowin", "Type a question or speak out using the mic button (1st button) to send a quesstion after typing the question click on send button (2nd button), you can click the 'Try... asking' Button for a list of questions you can try."))
        self.label_14.setText(_translate("infowin", "What can it do ?"))
        self.label_2.setText(_translate("infowin", "It can do alot of things for you if you are bored or lonely you can chat with MChat - Chatbot. It can also help you in your day to day life like open specific apps for you, to increase ease of use this version also has voice recognition."))
        self.label_15.setText(_translate("infowin", "How to use Speech recognition ?"))
        self.label_3.setText(_translate("infowin", "Click the Message Box, then press the Mic button speak out your message wait for a few seconds the message should appear on the message box, review the message and click send.\n\n *Note*: You might need to use another pair of microphones, there are know issues while using in-built Microphones"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    infowin = QtWidgets.QMainWindow()
    ui = Ui_infowin()
    ui.setupUi(infowin)
    infowin.show()
    sys.exit(app.exec_())
